server.port=8082
server.address=0.0.0.0

spring.application.name=order-service

spring.datasource.url=jdbc:mysql://localhost:3306/order_db
spring.datasource.username=root
spring.datasource.password=root@39

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.instance-id=${spring.application.name}:${random.value}
eureka.instance.prefer-ip-address=true
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

internal.api-key=0aK4VOyO5dOwBEBjJG6+cbio1ENbTNYVqi0elOkWnvo=

resilience4j.retry.instances.inventoryRetry.max-attempts=3
resilience4j.retry.instances.inventoryRetry.wait-duration=2s

resilience4j.circuitbreaker.instances.inventoryCB.sliding-window-size=5
resilience4j.circuitbreaker.instances.inventoryCB.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.inventoryCB.wait-duration-in-open-state=10s

feign.client.config.default.connectTimeout=5000
feign.client.config.default.readTimeout=5000

spring.cloud.openfeign.okhttp.enabled=true
spring.cloud.openfeign.httpclient.enabled=false

jwt.secret=0aK4VOyO5dOwBEBjJG6+cbio1ENbTNYVqi0elOkWnvo=